apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharedhousing-mongo
  labels:
    app: sharedhousing-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sharedhousing-mongo
  template:
    metadata:
      labels:
        app: sharedhousing-mongo
    spec:
      containers:
      - name: sharedhousing-mongo
        image: sharedhousing-mongo
        imagePullPolicy: Never
        ports:
        - containerPort: 27017
  