apiVersion: apps/v1
kind: Deployment
metadata:
  name: sh-db-deployment
  labels:
    app: SharedHousingDb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SharedHousingDb
  template:
    metadata:
      labels:
        app: SharedHousingDb
    spec:
      containers:
      - name: sh-db
        image: sh-db
        imagePullPolicy: Never
        ports:
        - containerPort: 80
  